### ISSUE TITLE
Can't access owncloud

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/owncloud_deployer#11]
After logging in with TFConnect i get redirected to a page that asks if i want to use the same email from TFConnect or a different email and when i press submit for any of the mentioned options i get the following message

![image](https://user-images.githubusercontent.com/101194226/163360724-65d60dd7-143c-439d-8798-d463ffc2d3f8.png)

and no email is sent to my inbox and i get this error in the console 

```
POST https://owncloud.threefold.io/owncloud/api/requests 409 (Conflict)
```

![image](https://user-images.githubusercontent.com/101194226/163360991-9e4135dc-aad8-40b3-8e00-4bf299205aa0.png)

**Comment by mohamedamer453** [comment]
I was using this already deployed instance https://owncloud.threefold.io/owncloud/ provided to me for testing purposes (did't deploy it myself) and after logging in with TFConnect i got this message  every time i pressed submit whether i changed the email or not i get the same error in the console and no emails were sent to my inbox.

**Comment by mohamedamer453** [comment]
It was the first time using my account to log into it. i will try to get more info about the deployment itself when, how it was deployed, and if it was configured correctly.

**Comment by hossnys** [comment]
@mohamedamer453  This instance is just for ops-use till now , i installed it just for testing the flow from operation perspective , and you already applied for a deployment with your mail 
![Screenshot from 2022-04-17 14-54-38](https://user-images.githubusercontent.com/26298009/163715208-7c889d4f-9c0a-498d-8e76-30551e5421d3.png)
and you didn't get any mail back as we didn't accept your request for deployment , please if you have a request for testing this product so fire your instance installation from scratch and test the whole process flow , that will be better .

**Comment by hossnys** [comment]
@sameh-farouk I'm closing this one as it's not an issue .
