### ISSUE TITLE
Deploying OwnCLoud with .tech email

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/owncloud_deployer#26]
It seems not all emails can work with the deployer, even though it's a valid domain name

![image](https://user-images.githubusercontent.com/65153287/166647280-a0cd7985-253f-4418-863f-86fada0644aa.png)

**Comment by xmonader** [comment]
relax the email rules a bit @sameh-farouk please

**Comment by dmitri-alleo** [comment]
But even after submitting the request (not with .tech domain) I didn't get any instructions to the email,
so I guess I need to wait until the 3-letter restriction is sorted out

**Comment by dmitri-alleo** [comment]
By the way, this check seems a bit odd, as there are many domains which are not just 2, 3 or 4 letters, there are domains like .online, .academy, .university, .education, .services, .business, .technology and so on

**Comment by xmonader** [comment]
@dmitri-alleo your instance is being deployed, requests need to be approved  
![image](https://user-images.githubusercontent.com/64129/166659279-5b88243f-1986-40d8-9dc6-02199fd86cd2.png)

**Comment by dmitri-alleo** [comment]
@xmonader how can I do it?
I didn't get any email in any of the email accounts.

**Comment by dmitri-alleo** [comment]
@xmonader should it come to the email address I have specified or the email address linked to the 3bot account?

**Comment by xmonader** [comment]
I just received an email on my alternate email that i specified.
![image](https://user-images.githubusercontent.com/64129/166660026-eea01ba8-2f72-466d-a1a6-7f84b53b3237.png)

**Comment by dmitri-alleo** [comment]
Aha, I see, it came, but it was placed into the promotions tab of Gmail, thanks

**Comment by dmitri-alleo** [comment]
Great, managed to create the user with the .tech email, so the restriction currently only applies on the request screen

![image](https://user-images.githubusercontent.com/65153287/166660689-9ad4bbef-eb6b-4172-b703-085bb5fa2b41.png)

**Comment by sameh-farouk** [comment]
> relax the email rules a bit @sameh-farouk please

On it.

**Comment by dmitri-alleo** [comment]
Having an issue today accessing my OwnCloud

![image](https://user-images.githubusercontent.com/65153287/166908062-aa450699-6b81-4139-821b-6ed29feee98e.png)

**Comment by sameh-farouk** [comment]
> Having an issue today accessing my OwnCloud
> 
> ![image](https://user-images.githubusercontent.com/65153287/166908062-aa450699-6b81-4139-821b-6ed29feee98e.png)

please refer to https://github.com/threefoldtech/test_feedback/issues/119

**Comment by sameh-farouk** [comment]
@dmitri-alleo the deployer instance on `https://ownclouddeployer.test.grid.tf` was updated today. you can check the new validation rules.

![Screenshot from 2022-05-13 01-29-19](https://user-images.githubusercontent.com/42457449/168183616-93d7ec18-d2cc-4d3b-b617-4745e030f026.png)

**Comment by dmitri-alleo** [comment]
Thank you @sameh-farouk

**Comment by sameh-farouk** [comment]
verified on 1.0.2 and https://ownclouddeployer.test.grid.tf
closing this. feel free to re-open the issue or open another one if you think it can be improved further. Thanks.
