### ISSUE TITLE
Files in ~/.config/jumpscale won't be backed up correctly.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/owncloud_deployer#31]
All files saved to `~/.config/jumpscale` are actually written to `/data/jsngmodel`.
`~/.config/jumpscale` is a symbolic link.

https://github.com/threefoldtech/owncloud_deployer/blob/2e643b5b7f77b929944dcffb889602e9feb410ba/docker/init.sh#L16

I'm not sure what is the added benefit of doing this, but I can see this being done too in TFTshop.

The downside is that the configured backup job will archive all Symlinks as symlinks, we don't back up the actual data.

From Restic [Docs](https://restic.readthedocs.io/en/latest/040_backup.html#backing-up-special-items-and-metadata)
> Symlinks are archived as symlinks, Restic does not follow them. When you restore, you get the same symlink again, with the same link target and the same timestamps.

**Comment by xmonader** [comment]
Believe that's mounted volume on the kubernetes cluster where it runs.

**Comment by sameh-farouk** [comment]
**Verified**
the symlinking no more happens when the container started.
