### ISSUE TITLE
Deployment failure after the instance was cleaned

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/owncloud_deployer#32]
After the deployment was cleaned i tried to deploy my instance again. Firstly i requested the instance but when i tired to confirm the deployment request i got this error

![image](https://user-images.githubusercontent.com/101194226/167359660-8316086a-4a9d-4773-b8da-47936d525512.png)

```
failed to deploy for user mohamedamer, error message:
cannot find config for mohamedamer at /root/.config/jumpscale/secureconfig/jumpscale/tools/terraform/terraform/Terraform/mohamedamer/data
```

**Comment by sameh-farouk** [comment]
@Mohamedamer45 I checked the error.  As the deployment service is always running, after cleaning the instances it has no idea that we deleted these instances, they still exist in memory but their config files have gone.  I restarted the server, and your deployment ran successfully.

**Comment by mohamedamer453** [comment]
verified and the deployment is working without any issue
