### ISSUE TITLE
Deployment Bad Gateway After uploading 1000 small files through webDav

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/owncloud_deployer#38]
I was testing the performance of uploading multiple small files and after the files were created and uploaded (all 1000 files were uploaded successfully) the instance failed to reload then it gave a `Bad Gateway` and i still can't access it although in the requests page the instance status is `Deployed` and it shows no errors.

![image](https://user-images.githubusercontent.com/101194226/168053300-b9adf3ae-7f2e-4e35-aab7-35bda49915b6.png)

The instance URL is available [here](https://owncloudmohamedamerqc7.gent02.test.grid.tf/)

### Steps that lead to this issue

- I connected ownCloud to Linux through webDav protocol by following the steps available [here](https://doc.owncloud.com/webui/next/classic_ui/files/access_webdav.html#accessing-files-using-linux).
- I navigated to the ownCloud Mount that was now available in my file directory.

![image](https://user-images.githubusercontent.com/101194226/168053928-c5fb8b25-8def-42fe-aaef-86ea27d6815e.png)

- Then i created a new directory and opened a terminal in it.
- And i executed the following script.
- ```for i in {0..1000}; do echo hello > "File$(printf "%03d" "$i").txt"; done;```
- After 19 mins the 1000 files were created successfully and i could see the files through the Web interface and from my file system.
- but a minute after the files were created the instance was unable to refresh and gave a `Bad Gateway` and it's still not working.

**Comment by sameh-farouk** [comment]
debugging this. 
you are getting this because the server is unreachable from the grid gateway.
I checked the deployment details. the machine is pingable at '303:6711:7494:64b:4d85:18bc:9d6f:b24', but can not ssh to it.

without having access to the VM I can not be sure what happened.

the node 199 - id 4399
I asked @muhamadazmy to check from the grid side what is could be wrong with this VM and wait for his input.

**Comment by sameh-farouk** [comment]
SSH failure was due to a bug with the [cloud-container](https://github.com/threefoldtech/cloud-container/issues/15)

Now we can't ssh to any Owncloud instance that was deployed before with the deployer. we have a workaround and will test it first then we properly will need to reset all the test instances and start over, so we can properly investigate any issue that could arise later.

**Comment by sameh-farouk** [comment]
all deployed instances including your deployment and the deployer itself had been canceled/deleted on May 13 due to an incident when the DevOps wallet ran out of tokens. so I'm afraid there is no way to understand what happened in this VM and caused the bad gateway error.

could you reproduce this issue on an Owncloud instance deployed from the play.dev.grid.tf? make sure you have added your ssh key to your weblets profile (ensure to add the comment/hostname part of the key as well as a workaround for the cloud-container bug).

**Comment by mohamedamer453** [comment]
i was able to reproduce the issue once again by deploying an ownCloud intance from [play.dev](https://play.dev.grid.tf/) and then i followed the same steps mentioned in the issues.
the 1000 files were created in 16 mins and after about a minute the instance gave a `Bad Gateway` and i still can't access it.

Instance [URL](https://oc39vm4a59245a.gent01.dev.grid.tf/)

i was able to ssh to the vm and i executed `zinit log` and here are the logs  [ownCloud_logs.txt](https://github.com/threefoldtech/owncloud_deployer/files/8695258/ownCloud_logs.txt)



here are the deployment details
```
{
    "version": 0,
    "contractId": 1865,
    "nodeId": 11,
    "name": "vmpczqgjc22e",
    "created": 1652624689,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-owncloud-10.9.1.flist",
    "publicIP": null,
    "planetary": "302:9e63:7d43:b742:d2e:78cb:a33c:b957",
    "interfaces": [
        {
            "network": "netpczqgjc22e",
            "ip": "10.1.2.2"
        }
    ],
    "capacity": {
        "cpu": 2,
        "memory": 16384
    },
    "mounts": [
        {
            "name": "diskpczqgjc22e",
            "mountPoint": "/var/lib/docker",
            "size": 107374182400,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
        "OWNCLOUD_DOMAIN": "oc39vm4a59245a.gent01.dev.grid.tf",
        "OWNCLOUD_ADMIN_USERNAME": "admin",
        "OWNCLOUD_ADMIN_PASSWORD": "Mohamedamer45312",
        "OWNCLOUD_MAIL_SMTP_SECURE": "none",
        "OWNCLOUD_MAIL_DOMAIN": "",
        "OWNCLOUD_MAIL_FROM_ADDRESS": "",
        "OWNCLOUD_MAIL_SMTP_HOST": "",
        "OWNCLOUD_MAIL_SMTP_PORT": "",
        "OWNCLOUD_MAIL_SMTP_NAME": "",
        "OWNCLOUD_MAIL_SMTP_PASSWORD": ""
    },
    "entrypoint": "/sbin/zinit init",
    "metadata": "",
    "description": "",
    "corex": false
}
```

The instance is still available for further debugging.

**Comment by sameh-farouk** [comment]
**Update:**
debugging this, 
- we were able to reproduce the issue, by scrolling fast through the dir of the 1000 files, this generates too many requests. the firefox dev console shows 1432 requests.
- we get 502 from the grid gateway, as it can't reach the configured backend (the server running the Owncloud).
- the actual error returned by accessing the instance directly with the ygg ip is connection refused. it will be acceptable if it is a temporary error (if the backlog of queued inbound connection requests has reached its maximum) but it isn't.
- access the machine by ssh and check the containers/services. still running fine and I can exec inside the
container and access port 8080, however, it's no longer being exposed on the host (more accurately the port is bound to only IPv4).

```sh
> ss -nltp | grep 80
LISTEN    0         0                  0.0.0.0:80               0.0.0.0:*        users:(("docker-proxy",pid=17416,fd=4))                                        
```

- A healthy instance shows both ports being exposed via docker-proxy e.g. 
```sh
> ps aux | grep docker-proxy
root     17416  0.0  0.0 1148624  968 ?        Sl   16:47   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.2 -container-port 8080
root     17423  0.0  0.0 1148880 2284 ?        Sl   16:47   0:00 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 80 -container-ip 172.18.0.2 -container-port 8080
```
- thanks to @OmarElawady he noted that on the affected server, the docker-proxy process that listens on port 80 on ipv6 and redirects them to the container's port dies.
```sh
root     17416  0.0  0.0 1148624  968 ?        Sl   16:47   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.2 -container-port 8080
root     17423  0.0  0.0      0     0 ?        Z    16:47   0:06 [docker-proxy] <defunct>
``` 
- restarting the container was able to restore the external access to the container, and the docker-proxy process was respawned. but we are looking for a proper fix.

-  strace suggests we are hitting a nofile limit
```
[pid  6811] <... pipe2 resumed>0xc0002eb490, O_NONBLOCK|O_CLOEXEC) = -1 EMFILE (Too many open files)
[pid  6810] <... setsockopt resumed>)   = 0
[pid  6811] read(1013,  <unfinished ...>
[pid  6806] epoll_pwait(6,  <unfinished ...>
[pid  6811] <... read resumed>"GET /remote.php/dav/files/admin/"..., 32768) = 1358
[pid  6810] accept4(4,  <unfinished ...>
[pid  6811] write(1023, "GET /remote.php/dav/files/admin/"..., 1358 <unfinished ...>
[pid  6806] <... epoll_pwait resumed>[], 128, 0, NULL, 165800) = 0
[pid  6811] <... write resumed>)        = 1358
[pid  6810] <... accept4 resumed>0xc0000adb88, [112], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EMFILE (Too many open files)
[pid  6811] read(1013,  <unfinished ...>
[pid  6806] futex(0xc000038d50, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  6811] <... read resumed>0xc000390000, 32768) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6810] futex(0xc000039150, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
```

- checking the docker-proxy nofile limit, the open file limit for this process is 1024.
```
root@vmpczqgjc22e:~# cat /proc/17423/limits | grep "open files"
Max open files            1024                 4096                 files
```

after raising the Docker daemon default limit for ulimit for nofile to 1000000 for our testing purposes we weren't able to reproduce the issue anymore. so this is a possible fix.

The next thing to try is disabling the Docker userland proxy and see if this can improve both the stability and performance of the server.

then I'll have done this properly on the owncloud flist.

**Comment by sameh-farouk** [comment]
another finding. it seems that dockerd has higher default limits than the ones we have on the VM.

in my laptop
```
sameh@sameh-inspiron-3576:~$ cat /proc/2058/limits 
Limit                     Soft Limit           Hard Limit           Units     
...
Max open files            1048576              1048576              files     
...     
```

but in the VM
```
root@vmpczqgjc22e:~# cat /proc/32319/limits 
Limit                     Soft Limit           Hard Limit           Units     
 ...
Max open files            1024                 4096                 files     
...
```

so docker operates on the VM with lower default limits for Max open files, and properly that is what causes this issue.

this happens because **we are not depending on the systemd/docker service file** to start the docker daemon **where it sets the limits properly**, I have a quick look at the standard service file, and here is the relevant part.

```
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
```

so for all our solutions where we run Docker, increasing the limits for the dockerd is required for performance and stability reasons.

**Comment by sameh-farouk** [comment]
this was fixed and released.

**Comment by mohamedamer453** [comment]
Verified through the ownCloud Deployer

The new Flist fixed the issue and i was able to create the same scenario but this time it didn't crash from the number of requests.

I also was able to stress test the instance by going through the 1000 files multiple times until the number of requests reached `4k+` as it can be seen below and the instance was stable and didn't crash throughout the whole test.

![image](https://user-images.githubusercontent.com/101194226/170503094-b0d4acec-907f-40cf-85d2-7b1e697d6876.png)
