### ISSUE TITLE
Owncloud Deployer: Terms & Conditions Checkbox

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/owncloud_deployer#41]
By default the `Submit` button is not disabled when the user leaves the checkbox unchecked 

![image](https://user-images.githubusercontent.com/101194226/166882499-b7ba57a1-8bf1-4cdb-80be-d8d550e7589d.png)

It only gets disabled when the user checks the box then unchecks  it again 

![image](https://user-images.githubusercontent.com/101194226/166882386-fae0d7f1-4ac8-4582-8f02-0d63d45f9d80.png)

**Comment by sameh-farouk** [comment]
duplicated https://github.com/threefoldtech/owncloud_deployer/issues/46
