### ISSUE TITLE
Login to OwnCloud with TFT credentials

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/owncloud_deployer#42]
Basically managed to login successfully when creating a new user (automatically created when trying to login with a Threefold App) 

it seems to be a workaround when a script triggers the creation of a new user instead of allowing the existing user to be integrated into the Threefold authorization, because if you already have a user provided via email and you have set your environment set up, transferred files, configured templates etc., 

you would want to connect with the same user via Trheefold App authorization, not crreating a new user.

In this case it should clearly state NOT "Login with Threefold App", but rather "Create a new user with Threefold App"

**Comment by xmonader** [comment]
This is out of the scope, the system assumes you have one admin account with user/password and as many `new` users coming in with threefold connect app.
