### ISSUE TITLE
Connect Google Drive to OwnCloud as external storage documentation

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/owncloud_deployer#43]
From the OwnCloud side the documentatino for connecting shows https://doc.owncloud.com/server/10.8/admin_manual/configuration/files/external_storage/google.html#preparations-in-the-google-cloud-console

The documentation must be a bit outdated, as it doesn't exactly match the steps which need to be done

In the beginning, when creating a new application, these steps don't match exactly

![image](https://user-images.githubusercontent.com/65153287/168117034-3b710e7c-5699-436d-be16-71b1d8649013.png)

![image](https://user-images.githubusercontent.com/65153287/168117115-4be3995c-ee64-4839-be14-9fa1719daf41.png)

Then when creating the APIs access for the application

1st step:
OwnCloud documentation:
![image](https://user-images.githubusercontent.com/65153287/168115960-b2afba06-f787-4a35-a6b0-53a20a8c5a89.png)

Google Cloud
![image](https://user-images.githubusercontent.com/65153287/168115896-88ce1881-30d5-4329-8b20-1d10bec5aaaf.png)

2nd step:
OwnCloud documentation:
![image](https://user-images.githubusercontent.com/65153287/168116193-9e13ce3a-0a6d-4d0d-b875-f34bde215888.png)

Google drive
![image](https://user-images.githubusercontent.com/65153287/168116309-8c089faa-7e06-4457-bb71-dcde52499590.png)

![image](https://user-images.githubusercontent.com/65153287/168116377-ef99cd9c-69d7-4ac3-8728-b1bdb7cb45bd.png)

There rest of the steps is easier to figure out, it was the first time searching for where Google has placed the Google Drive APIs for the created application

**Comment by sameh-farouk** [comment]
if their docs have something which outdated or poorly documented and this is causing confusion this should be reported on their repo https://github.com/owncloud/docs, the deployer has nothing to do with this.

having said that, the link you shared gives 404, and from the URL I can see you are accessing the docs for the old version (10.8), maybe if you refer to the current version docs (10.10), info could be more updated.
see this for latest docs
https://doc.owncloud.com/server/10.10/admin_manual/configuration/files/external_storage/google.html
