### ISSUE TITLE
OwnCloud deployer "terms and conditions" checkbox validation fail

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/owncloud_deployer#46]
On the latest versino of OwnCloud deployer instance when the email is added correctly (the 3-letter domain error was fixed), it still shows the "Submit" button as enabled even if the "terms and conditions checkbox is not checked

![image](https://user-images.githubusercontent.com/65153287/168984618-eac38860-edc1-40f3-a892-0b466786118e.png)

**Comment by sameh-farouk** [comment]
**fixed now on 87a1e482305c76c41cd23bfe39ee381b5179b3bf** and released.

you can verify on the staging server https://ownclouddeployer.test.grid.tf/owncloud/#/

**Comment by mohamedamer453** [comment]
Verified on https://ownclouddeployer.test.grid.tf/ 

The `Submit` button is now disabled by default and will not work until the Terms & Conditions checkbox is checked.

![image](https://user-images.githubusercontent.com/101194226/170482245-86617824-2c48-4b41-af3b-d72dcbfb272e.png)

either when the default email is used or when a new email is entered

![image](https://user-images.githubusercontent.com/101194226/170482363-de352737-8e75-45c2-aba6-a07ea738a921.png)

![image](https://user-images.githubusercontent.com/101194226/170482506-06e3b01f-b2f5-4a70-95da-a7545dec1229.png)
