### ISSUE TITLE
No.31 - Test case: TC638 owncloud UI is different than its documentation

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/owncloud_deployer#48]
Version v1.4.1-rc2
Deployed on Testnet

Ex res: 
https://doc.owncloud.com/webui/next/classic_ui/webinterface.html#navigating-the-main-user-interface
![image](https://user-images.githubusercontent.com/65153287/169531268-4bdffcd4-627d-4340-b4dd-b72350a18405.png)

Actual res: 
![screenshoteasy - 2022-05-20T154648 367](https://user-images.githubusercontent.com/65153287/169531294-97965e23-262a-4777-9376-58666d85536c.png)

**Comment by sameh-farouk** [comment]
@xmonader we use 10.9.1 stable, and Owncloud 10.10 was just released seven days ago. probably the image reference an older version and they didn't update the images in their docs as UI changes were minimum.
