### ISSUE TITLE
'TF Connect' login method does not work.

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/owncloud_deployer#53]
Once an Owncloud is deployed, logging in with the email user works but using 'TF Connect' does not.

![image](https://user-images.githubusercontent.com/88312671/179001797-2a06969a-1df6-4078-883a-6fc30cec8987.png)

**Comment by scottyeager** [comment]
I think this forum [post](https://forum.threefold.io/t/owncloud-experience-and-problems/2769/7) may be relevant. TF Connect accounts need to be activated in a specific way from within the interface. Would certainly be nice to have this set automatically for users who come in through the deployer.

**Comment by sameh-farouk** [comment]
you need to log in with the admin credentials sent to your email and enable/approve any TF Connect accounts. this is done to protect the server from unauthorized access. otherwise, anyone with a threefold account can utilize your server resources.

**Comment by coesensbert** [comment]
Aha makes sense, thought it was maybe linked to the email address linked to your TF Connect account.
Should this maybe be clearly described in the email send to the user? So they know to activate it.

**Comment by coesensbert** [comment]
related: https://github.com/threefoldtech/owncloud_deployer/issues/56

**Comment by sameh-farouk** [comment]
@coesensbert if this is still relevant, you can open a feature request. closing this as the login method works fine.
