### ISSUE TITLE
Deployment info received on different email address

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/owncloud_deployer#54]
It says my deployment info will be sent to sabrina_sadik@hotmail.com, but I got it on sabrina@threefold.tech
![Screenshot 2022-07-14 at 15 23 34](https://user-images.githubusercontent.com/31733464/179002217-84415e29-e7a8-47de-a695-23b76cf317bb.png)

**Comment by sameh-farouk** [comment]
If you filled the input box with an address it will be used instead. if you want to receive the credentials on your TF connect email, you should leave that box empty.
