### ISSUE TITLE
Deployment info email received, but can't login since 'user is disabled' 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/owncloud_deployer#55]
User trout2 received his email, but can't seem to login.

![photo_2022-07-14 16 11 31](https://user-images.githubusercontent.com/31733464/179002848-d1c6d174-70b4-4463-95af-8196a5ef92dc.jpeg)

**Comment by coesensbert** [comment]
Did he also use the TF Connect login method? If so the user/password in the email should work.

https://github.com/threefoldtech/owncloud_deployer/issues/53

**Comment by sameh-farouk** [comment]
Duplicate of #53
